[pytest]
pythonpath = .
testpaths = tests
addopts =
    --tracing=retain-on-failure
    --video=retain-on-failure
    --screenshot=only-on-failure
    --html=reports/report.html
    --self-contained-html